name = "backend"
compatibility_date = "2023-12-01"
account_id = "f46d7a7239ab528fb664e7d1f8025f40"
workers_dev = true

[vars]
DATABASE_URL=""
JWT_SECRET="4789234n23kj423kj423kjb423hjb4k2j3bk2j3b"


[[r2_buckets]]
binding = 'MY_BUCKET'
bucket_name = 'image'