name = "backend"
compatibility_date = "2023-12-01"
account_id = "f46d7a7239ab528fb664e7d1f8025f40"
workers_dev = true

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNzk5NWE0YTYtOTg4Ny00MDJiLWFkYzAtYzdmOTI2NjU1ZGM1IiwidGVuYW50X2lkIjoiZTY2NmM5NDE5NDdlZmEwNDI1NTU1NGFmODllMWRjZmI5NGQ3N2E3NDJmZmZiYzY5NzY4NDI0ZDMxOGYyMDY3OCIsImludGVybmFsX3NlY3JldCI6ImI3YzA4MmMyLTlhNTAtNDc2My04YjAwLTZmNzc2NTRmNmVmMiJ9.OLYlzA5f7QhKzvKAGHC9yjxHn6ChqfkxEOiVByS63A4"

JWT_SECRET="4789234n23kj423kj423kjb423hjb4k2j3bk2j3b"


[[r2_buckets]]
binding = 'MY_BUCKET'
bucket_name = 'image'